### ISSUE TITLE
Bug with gffread when converting gff3 to gtf

### ISSUE THREAD

**Issue by kokonech** [cole-trapnell-lab/cufflinks#11]
I detected a bug in gffread when converting gff3 to gtf using Cufflinks v.2.2.1 on Linux.

The gff3 file called all.gff3 can be downloaded from here:
ftp://ftp.plantbiology.msu.edu/pub/data/Eukaryotic_Projects/o_sativa/annotation_dbs/pseudomolecules/version_7.0/all.dir/

This file was converted to gtf using gffread:

$ gffread all.gff3 -T -o all.gtf

Check the exon coordinates of transcript LOC_Os06g46770.3 in gff3 file:

$ grep LOC_Os06g46770.3 all.gff3 | grep exon

Chr6    MSU_osa1r7    exon    28401731    28401808    .    +    .    ID=LOC_Os06g46770.3:exon_1;Parent=LOC_Os06g46770.3
Chr6    MSU_osa1r7    exon    28402585    28403489    .    +    .    ID=LOC_Os06g46770.3:exon_2;Parent=LOC_Os06g46770.3
Chr6    MSU_osa1r7    exon    28403718    28404585    .    +    .    ID=LOC_Os06g46770.3:exon_3;Parent=LOC_Os06g46770.3

Then check the same in a new gtf file:

$ grep LOC_Os06g46770.3 all.gtf | grep exon

Chr6    MSU_osa1r7    exon    28401731    28401808    .    +    .    transcript_id "LOC_Os06g46770.3"; gene_id "LOC_Os06g46770"; gene_name "LOC_Os06g46770";
Chr6    MSU_osa1r7    exon    28402585    28404585    .    +    .    transcript_id "LOC_Os06g46770.3"; gene_id "LOC_Os06g46770"; gene_name "LOC_Os06g46770";
Chr6    MSU_osa1r7    exon    28403718    28404585    .    +    .    transcript_id "LOC_Os06g46770.3"; gene_id "LOC_Os06g46770"; gene_name "LOC_Os06g46770";

As you can see now the coordinates of exon2 and exon3 are wrong, they have the same end point.

**Comment by gpertea** [comment]
Indeed, that output is wrong, but to be fair, the CDS and 3'UTR features of this mRNA seem wrong as well (or at least very unusual) in that file - no wonder the parser got confused. If you show all the features for that mRNA this is what you get (simplified and reordered by me for clarity):

 Chr6	MSU_osa1r7	mRNA	28401731	28404585	.	+	.	ID=LOC_Os06g46770.3
 Chr6	MSU_osa1r7	5UTR	28401731	28401808	.	+	.	Parent=LOC_Os06g46770.3
 Chr6	MSU_osa1r7	exon	28401731	28401808	.	+	.	Parent=LOC_Os06g46770.3
 Chr6	MSU_osa1r7	exon	28402585	28403489	.	+	.	Parent=LOC_Os06g46770.3
 Chr6	MSU_osa1r7	CDS	28402585	28403261	.	+	.	Parent=LOC_Os06g46770.3
 Chr6	MSU_osa1r7	3UTR	28403262	28403489	.	+	.	Parent=LOC_Os06g46770.3
 Chr6	MSU_osa1r7	CDS	28403490	28404186	.	+	.	Parent=LOC_Os06g46770.3
 Chr6	MSU_osa1r7	exon	28403718	28404585	.	+	.	Parent=LOC_Os06g46770.3
 Chr6	MSU_osa1r7	3UTR	28404187	28404585	.	+	.	Parent=LOC_Os06g46770.3

The 2nd CDS there just seems to just follow the 1st 3' UTR (?) and then covers the intron between 2nd and 3rd exons and it then extends into the 3rd exon.. And that is then unusually followed by the 2nd 3' UTR (?). So we have this unusual chain of adjacent features bridging exons 2 and 3: 
 CDS+3'UTR+CDS+3'UTR
The parser simply extended the overlapped exons to accommodate these unusual features but did not merge them into a single exon.. Not sure what to do with that - perhaps those two CDS+3' UTR pairs are just variants of the same basic transcript (i.e. different isoforms)? But then they should've been correctly defined as such in the GFF3 file, with a different mRNA ID etc.

**Comment by kokonech** [comment]
Right, there is mistake with the annotation file. I did not detect it because I was only interested in exon coordinates without 5UTR, CDS and 3UTR. Perhaps it would be great if such "wrong" genes are skipped and a warning is reported.

**Comment by ctrapnell** [comment]
Fixing this would really require adding more GTF/GFF sanity checking and validation than we are willing to invest in for the forseeable future.
