### ISSUE TITLE
bam/version.hpp not found

### ISSUE THREAD

**Issue by kennethphough** [cole-trapnell-lab/cufflinks#14]
When I configure cufflinks on CentOS 7 with libbam installed in '/usr/local/' I get the following error:

checking for bamlib... configure: error: We could not detect the bam libraries (version  or higher). If you have a staged bam library (still not installed) please specify $BAM_ROOT in your environment and do not give a PATH to --with-bam option.  If you are sure you have bam installed, then check your version number looking in bam/version.hpp. See http://randspringer.de/bam for more documentation.

After tracking down the issue and making sure permissions where set correctly I realised that there is no "version.hpp".  I downloaded Samtools 1.1 and it contains "version.h".  Changing the configure file fixed the issue and cufflinks compiled correctly.  Is this a bug or am I compiling Cufflinks incorrectly?

Thanks in advance,
Ken

**Comment by chebyshev** [comment]
Ken,
I experienced the same issue. samtools 1.X is htslib based. Try samtools 0.X.
http://sourceforge.net/projects/samtools/files/samtools/
Looks 0.1.20 is the latest but I used 0.1.19 and works fine.

best,

**Comment by loveshack** [comment]
For what it's worth, the srpm at http://arc.liv.ac.uk/downloads/misc/SRPMS/cufflinks-2.2.1-2.el6.src.rpm will build on centos7  with the samtools rpm from https://copr.fedoraproject.org/coprs/loveshack/livhpc/.  I think it has a fiddle to get the packaged headers picked up in the build.

**Comment by kennethphough** [comment]
Thanks for the help! (and sorry for the delay)
