### ISSUE TITLE
will samtools dependency change to packaged with cufflinks?

### ISSUE THREAD

**Issue by kotoroshinoto** [cole-trapnell-lab/cufflinks#20]
is cufflinks going to break from external samtools like tophat did? samtools split into 3 projects now, though it still compiles much the same way (if you pull the repos and attempt to build samtools it seem to automatically try to depend on the other libraries and assumes they're in the same directory if you don't give it a path manually).

I don't mind if it does, but just try to be careful not to break the ability to do an out-of-source build like tophat did.

**Comment by ctrapnell** [comment]
We'll need to look carefully how the samtools API got divvied up.  I'm not scheduling this for the upcoming 2.3.0 release, so we'll have to add a note to build against samtools 1.19 + for now.  But we likely won't be packaging samtools like TopHat did.
