### ISSUE TITLE
Bug in gffread when indexing fasta files with empty lines

### ISSUE THREAD

**Issue by drchriscole** [cole-trapnell-lab/cufflinks#23]
Empty lines between fasta entries in file provided via the -g switch throws error at line 117 in GFastaIndex.cpp

Workaround is either to pre-index file with samtools - handles blank lines fine - or remove blank line in fasta file.

**Comment by kotoroshinoto** [comment]
I'm not on the dev team but I suspect they might want to know more about the structure of the input files.

Do they have multiple empty lines in a sequence or just one empty line between entries?

**Comment by kotoroshinoto** [comment]
or is the a gap between the label and the sequence (within the bounds of a single entry)

**Comment by drchriscole** [comment]
The entries have valid sequence in them, but there is an additional blank space between the end of one entry and the start of the next e.g.

    >Seq1
    CACTCTACTACTATCATCTTCAACGA
    
    >Seq2
    CCGTCATCGTAGTGATGCTAGCTAGCTGTAGCTGA

It's arguable whether that's a valid fasta file, but I think the code could be better written to not assume that two adjacent lines of unequal length is an error, which is essentially what the error in GFastaIndex.cpp is reporting.

**Comment by gpertea** [comment]
Agreed - I'll fix this.

**Comment by drchriscole** [comment]
Great. Thanks.

**Comment by kotoroshinoto** [comment]
usually if I write custom fasta parsers i just have an early check for lines that are blank (or completely composed of whitespace) and just flat out ignore all blank lines. Its fairly permissive, but it sidesteps problems like this.

**Comment by drchriscole** [comment]
The whitespace highlighted a more general issue about line length which is the problem here.
