### ISSUE TITLE
Cuffquant "usage" information is wrong --- it's the instructions for cuffdiff instead of cuffquant

### ISSUE THREAD

**Issue by alexgraehl** [cole-trapnell-lab/cufflinks#24]
Line 91 in : https://github.com/cole-trapnell-lab/cufflinks/blob/master/src/cuffquant.cpp

It gives the usage information for cuffDIFF, not cuffQUANT. In particular, it says that cuffquant supports multiple *different* BAM/SAM samples, comma-delimited which appears not to be the case according to the help on the web.

**Comment by cbrueffer** [comment]
This was fixed in 361b704c28eb9e5eb2b6381076c04b286226aea1 in the develop branch in December 2014, but has not been merge back to master yet.

**Comment by ctrapnell** [comment]
I’m planning on a new release that pushes out this an many other fixes, large and small, soon.  I’ve been on a grant writing and travel bender, but the rest of the summer is more free.  It’s also taken me a while to move my integration test suite from Harvard to UW, but that’s mostly up and running now.  Stay tuned.


Cole Trapnell, Ph.D.Assistant Professor

Department of Genome Sciences

University of Washington

**Comment by alexgraehl** [comment]
Awesome! I'll be installing it as soon as it's ready!

 Alex

**Comment by dsenalik** [comment]
The develop branch of cuffquant.cpp still lists "-c/--min-alignment-count" as an option in the usage (line 107), but there is no code to handle this option
