### ISSUE TITLE
Sam file of collapsed reads

### ISSUE THREAD

**Issue by liangcmu** [cole-trapnell-lab/cufflinks#28]
I have SAM files that are different from general SAM files.  For a given FASTQ data from RNA-Seq project, we first collapsed the reads in terms of sequence content to get rid of redundancy and obtain a much smaller FASTA file, like 

>1_356780
ATGACTA....
>2_234565
AAATTTTCAT...

Here, the expression information or count is embedded inside the sequence name.  For the above example, the first sequence has 356780 copies or count within the individual FASTQ data, while the second sequence has 234565 copies.  Such collapsing really saved us a lot of time in read-to-genome mapping.  Consequently, in our SAM file obtained using this collapsed reads, the expression count data for each collapsed read is also embedded inside the name. 

My question is how can we use cuffquant for our special SAM files generated using collapsed reads?   Can we use this kind of SAM file to get expression data for individual genes/transcripts from cufflinks, and then multiple the expression data with the aforementioned expression counts to get the final expression count number?  I am afraid that this multiplication might not be correct and will inflate the expression number.  Any comment or suggestion will be highly appreciated.

**Comment by ctrapnell** [comment]
We don't support this kind of input, and will not add support in the future unless it becomes a required part of the SAM specificiation.
