### ISSUE TITLE
thought you guys should be made aware of this samtools response to an issue i had

### ISSUE THREAD

**Issue by kotoroshinoto** [cole-trapnell-lab/cufflinks#29]
https://github.com/samtools/samtools/issues/403

the instructions in your getting started page are somewhat old, as is the manner in which libbam is being depended on. Perhaps switching to htslib would make more sense than doing what tophat's group did and freezing samtools versions.

**Comment by ctrapnell** [comment]
I would like to, but that would be a significant amount of maintenance time I just don't have right now.

**Comment by kotoroshinoto** [comment]
That is understandable, but it should still be somewhere on the todo list with low priority status. 

If I understood your respective codebases well enough i'd be willing to do it myself, but alas I don't have that much time either, so believe me when I say I understand.

**Comment by kotoroshinoto** [comment]
I still highly disagree with what tophat's group tends to do, their decision to version freeze is bound to lead to future issues. Their use of SeqAn-1.3 is already causing an issue with gcc 5.1. It is highly likely we'll see a problem with their samtools version freeze at some point.
