### ISSUE TITLE
Cuffdiff 2

### ISSUE THREAD

**Issue by liangcmu** [cole-trapnell-lab/cufflinks#34]
In your Nature Biotechnology paper, 2013 31(1):46-53, you have described Cuffdiff 2. 

I already obtained SAM files after aligning RNA-Seq reads to the reference genome. I only need to use Cuffdiff 2 to conduct the downstream analysis. Where can I download the codes for Cuffdiff 2, as described in this paper? Thank you for clarification.

**Comment by ctrapnell** [comment]
Please post this kind of questions to https://groups.google.com/forum/#!forum/tuxedo-tools-users, not here.
