### ISSUE TITLE
after download master cufflinks binary files, I can not find the executable files?

### ISSUE THREAD

**Issue by myRNASeq** [cole-trapnell-lab/cufflinks#37]
Hi Guys,
Following "Installing a pre-compiled binary release" (http://cole-trapnell-lab.github.io/cufflinks/getting_started/#installing-a-pre-compiled-binary-release), I downloaded the pre-compiled ZIP file cufflinks-master.zip and unzipped it, however I can not find the cufflinks,cuffdiff and cuffcompare binaries files in the folder.
What should I do?

Thanks in advance!

**Comment by ctrapnell** [comment]
Sounds like you downloaded a source package from the GitHub page.  You need to look here:

http://cole-trapnell-lab.github.io/cufflinks/install/
