### ISSUE TITLE
Please make some tags that correspond to your release versions

### ISSUE THREAD

**Issue by xguse** [cole-trapnell-lab/cufflinks#43]
It is extremely helpful for folks trying to grab/correlate specific versions to be able to:

```
git clone repo/address.git
git checkout vX.X.X
```

It also helps greatly when building package recipes for things like [conda](http://conda.pydata.org/docs/building/recipe.html) which is what I am doing now.

Thanks

**Comment by jrdemasi** [comment]
Can I bump this?  Not a hard thing to do, but makes reproducible research a possibility.  You're going to drive people away from your own project... 6 months later, the issue is opened but no progress!? This would take less than 20 minutes of someone's time.  If I have to submit a pull request just for this, I will, but at least say so..

**Comment by greysAcademicCode** [comment]
:+1:
@ctrapnell @adarob Why not tag your stable releases here?

**Comment by ctrapnell** [comment]
The Cufflinks github repo was imported from a private SVN repository and it didn't bring our release tags across. Adding tags for previous releases would require that I got back and manually match up commits to releases. I don't have time for that. We will tag future point releases.

**Comment by jrdemasi** [comment]
@ctrapnell Isn't the whole point of research to be able to reproduce?  If someone wants to go back and use an old version to replicate results, they're going to be SoL.

**Comment by greysAcademicCode** [comment]
Can you please at least tag one single (the latest) release? Wouldn't it take literally 30 sec to cross-reference the commit hash? I don't think we really need tags for all the old releases.

**Comment by ctrapnell** [comment]
@jrdemasi No, they're not SoL. We have tarballs of all the releases going back to 0.7.0 on the website. The source code is available.

**Comment by jrdemasi** [comment]
@ctrapnell Sure, but that isn't immediately evident from someone who lands at your GH instead of your website.  Further, if you have the source already tarred, you could stage them as commits and tag them.

**Comment by ctrapnell** [comment]
@greysAcademicCode The 2.2.1 release is now tagged. I will try to release the HEAD as 2.2.2 soon.

**Comment by ctrapnell** [comment]
@jrdemasi: There's a link to the main website literally at the top of the README. I've added a link to the page with the old tarballs. That's as much as I have time to do on this one.

**Comment by greysAcademicCode** [comment]
@ctrapnell Thanks! I'm packaging your work up in the Arch User Repo so that it's easy for anyone using Arch Linux to install: https://aur.archlinux.org/packages/cufflinks/
