### ISSUE TITLE
 sci-biology/cufflinks-2.2.1 can't be compiled in a 64 Bit Gentoo chroot image

### ISSUE THREAD

**Issue by toralf** [cole-trapnell-lab/cufflinks#6]
It failed in stl_pair.h:119:39: error: no matching function for call to ‘boost::shared_ptr<void>
see https://bugs.gentoo.org/show_bug.cgi?id=535716 for the full error msg.

**Comment by ctrapnell** [comment]
This is a duplicated of #3
