### ISSUE TITLE
cufflink doesn't compile with last R version

### ISSUE THREAD

**Issue by sistemas-scbi** [cole-trapnell-lab/cufflinks#8]
Hi,

The problem is that in RSQLite the function sqliteQuickSQL has been deprecated, so it cannot be used anymore, and programs that used to work now don't work with an updated R.

So cufflink cannot be installed with the last R version, it says:

Error : object ‘sqliteQuickSQL’ is not exported by 'namespace:RSQLite'
Error: package ‘Gviz’ could not be loaded

Could someone solve that problem ?

Thanks,

Rafael

**Comment by ctrapnell** [comment]
Cufflinks doesn't run on R. Perhaps you mean CummeRbund?

**Comment by sistemas-scbi** [comment]
Yes, you are right, sorry for the confusion.
